<?php 
    require('header.php'); 
    require('contentIndex.html');
    require('footer.php'); 
    echo("
        <script>
            window.onload(setInterval(changerRandomImg,3500)) 
        </script>
        ")
?>
